version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=local
      - SECRET_KEY=your-secret-key
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:54322/postgres
