# This workflow is used to test the API routes and ensure they are working as expected
# Deployment will occur only if all tests pass, as configured by the host provider

name: Test FastAPI App

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'reco/**'

  push:
    branches:
      - main
    paths:
      - 'reco/**'
jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r reco/planwise/requirements.txt

      - name: Run unittests
        run: |
            python -m unittest discover -s reco/planwise/tests
